//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        internal static string chkRememberPassword_Text {
            get {
                return ResourceManager.GetString("chkRememberPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  time.
        /// </summary>
        internal static string frmLoginCap_CountTime_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_CountTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account and password.
        /// </summary>
        internal static string frmLoginCap_Enter_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_Enter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during login: .
        /// </summary>
        internal static string frmLoginCap_Error_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_Error.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string frmLoginCap_LoginSuccessful_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_LoginSuccessful.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered wrong password 3 times, software will close now!.
        /// </summary>
        internal static string frmLoginCap_noticeClosed_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_noticeClosed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not correct, do you want to create a new user?.
        /// </summary>
        internal static string frmLoginCap_noticeNotFound_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_noticeNotFound.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name .
        /// </summary>
        internal static string frmLoginCap_UserName_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_UserName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password .
        /// </summary>
        internal static string frmLoginCap_WrongPassword_Text {
            get {
                return ResourceManager.GetString("frmLoginCap_WrongPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconAboutSoftware {
            get {
                object obj = ResourceManager.GetObject("iconAboutSoftware", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconAppointmentScheduleReport {
            get {
                object obj = ResourceManager.GetObject("iconAppointmentScheduleReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconBackupandRestoreDatabase {
            get {
                object obj = ResourceManager.GetObject("iconBackupandRestoreDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconChangePassword {
            get {
                object obj = ResourceManager.GetObject("iconChangePassword", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconClose {
            get {
                object obj = ResourceManager.GetObject("iconClose", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconContactSupport {
            get {
                object obj = ResourceManager.GetObject("iconContactSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconDarkMode {
            get {
                object obj = ResourceManager.GetObject("iconDarkMode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconDarkMode_ {
            get {
                object obj = ResourceManager.GetObject("iconDarkMode_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconExit {
            get {
                object obj = ResourceManager.GetObject("iconExit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconInventoryandMedicineRevenueReport {
            get {
                object obj = ResourceManager.GetObject("iconInventoryandMedicineRevenueReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLightMode {
            get {
                object obj = ResourceManager.GetObject("iconLightMode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLogin {
            get {
                object obj = ResourceManager.GetObject("iconLogin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconLogout {
            get {
                object obj = ResourceManager.GetObject("iconLogout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageAppointments {
            get {
                object obj = ResourceManager.GetObject("iconManageAppointments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageDoctors {
            get {
                object obj = ResourceManager.GetObject("iconManageDoctors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageExaminationHistory {
            get {
                object obj = ResourceManager.GetObject("iconManageExaminationHistory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageMedicineInventory {
            get {
                object obj = ResourceManager.GetObject("iconManageMedicineInventory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManagePatients {
            get {
                object obj = ResourceManager.GetObject("iconManagePatients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManagePrescription {
            get {
                object obj = ResourceManager.GetObject("iconManagePrescription", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconManageUserAccounts {
            get {
                object obj = ResourceManager.GetObject("iconManageUserAccounts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconPatientListReport {
            get {
                object obj = ResourceManager.GetObject("iconPatientListReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconUSA {
            get {
                object obj = ResourceManager.GetObject("iconUSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconUserGuide {
            get {
                object obj = ResourceManager.GetObject("iconUserGuide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconVietNam {
            get {
                object obj = ResourceManager.GetObject("iconVietNam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconVietNam_ {
            get {
                object obj = ResourceManager.GetObject("iconVietNam_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconViewActivityLog {
            get {
                object obj = ResourceManager.GetObject("iconViewActivityLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] imgfrmCreateAccount {
            get {
                object obj = ResourceManager.GetObject("imgfrmCreateAccount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] imgfrmLoginForm {
            get {
                object obj = ResourceManager.GetObject("imgfrmLoginForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string lblHello_Text {
            get {
                return ResourceManager.GetString("lblHello.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where health begins, technology leads the way.
        /// </summary>
        internal static string lblLogan_Text {
            get {
                return ResourceManager.GetString("lblLogan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string lblLogin_Text {
            get {
                return ResourceManager.GetString("lblLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string llblDontHaveAnAccount_Text {
            get {
                return ResourceManager.GetString("llblDontHaveAnAccount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string llblForgotPassword_Text {
            get {
                return ResourceManager.GetString("llblForgotPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string notification_Text {
            get {
                return ResourceManager.GetString("notification.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string tabPageAppointments_Text {
            get {
                return ResourceManager.GetString("tabPageAppointments.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string tabPageDoctors_Text {
            get {
                return ResourceManager.GetString("tabPageDoctors.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Inventory.
        /// </summary>
        internal static string tabPageMedicineInventory_Text {
            get {
                return ResourceManager.GetString("tabPageMedicineInventory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string tabPagePatients_Text {
            get {
                return ResourceManager.GetString("tabPagePatients.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Software.
        /// </summary>
        internal static string tsmiAboutSoftware_Text {
            get {
                return ResourceManager.GetString("tsmiAboutSoftware.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment ScheduleReport.
        /// </summary>
        internal static string tsmiAppointmentScheduleReport_Text {
            get {
                return ResourceManager.GetString("tsmiAppointmentScheduleReport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup And Restore Database.
        /// </summary>
        internal static string tsmiBackupAndRestoreDatabase_Text {
            get {
                return ResourceManager.GetString("tsmiBackupAndRestoreDatabase.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string tsmiChangePassword_Text {
            get {
                return ResourceManager.GetString("tsmiChangePassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Support.
        /// </summary>
        internal static string tsmiContactSupport_Text {
            get {
                return ResourceManager.GetString("tsmiContactSupport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string tsmiExit_Text {
            get {
                return ResourceManager.GetString("tsmiExit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string tsmiFile_Text {
            get {
                return ResourceManager.GetString("tsmiFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tsmiHelp_Text {
            get {
                return ResourceManager.GetString("tsmiHelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory And Medicine Revenue Report.
        /// </summary>
        internal static string tsmiInventoryAndMedicineRevenueReport_Text {
            get {
                return ResourceManager.GetString("tsmiInventoryAndMedicineRevenueReport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string tsmiLogin_Text {
            get {
                return ResourceManager.GetString("tsmiLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string tsmiLogout_Text {
            get {
                return ResourceManager.GetString("tsmiLogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        internal static string tsmiManageAppointments_Text {
            get {
                return ResourceManager.GetString("tsmiManageAppointments.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Doctors.
        /// </summary>
        internal static string tsmiManageDoctors_Text {
            get {
                return ResourceManager.GetString("tsmiManageDoctors.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Examination History.
        /// </summary>
        internal static string tsmiManageExaminationHistory_Text {
            get {
                return ResourceManager.GetString("tsmiManageExaminationHistory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Medicine Inventory.
        /// </summary>
        internal static string tsmiManageMedicineInventory_Text {
            get {
                return ResourceManager.GetString("tsmiManageMedicineInventory.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string tsmiManagement_Text {
            get {
                return ResourceManager.GetString("tsmiManagement.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patient.
        /// </summary>
        internal static string tsmiManagePatient_Text {
            get {
                return ResourceManager.GetString("tsmiManagePatient.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Prescriptions.
        /// </summary>
        internal static string tsmiManagePrescriptions_Text {
            get {
                return ResourceManager.GetString("tsmiManagePrescriptions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Accounts.
        /// </summary>
        internal static string tsmiManageUserAccounts_Text {
            get {
                return ResourceManager.GetString("tsmiManageUserAccounts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Examination.
        /// </summary>
        internal static string tsmiPatientExamination_Text {
            get {
                return ResourceManager.GetString("tsmiPatientExamination.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient List Report.
        /// </summary>
        internal static string tsmiPatientListReport_Text {
            get {
                return ResourceManager.GetString("tsmiPatientListReport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports..
        /// </summary>
        internal static string tsmiReports_Text {
            get {
                return ResourceManager.GetString("tsmiReports.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string tsmiSystem_Text {
            get {
                return ResourceManager.GetString("tsmiSystem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        internal static string tsmiUserGuide_Text {
            get {
                return ResourceManager.GetString("tsmiUserGuide.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Activity Log.
        /// </summary>
        internal static string tsmiViewActivityLog_Text {
            get {
                return ResourceManager.GetString("tsmiViewActivityLog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword_Text {
            get {
                return ResourceManager.GetString("txtPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string txtUserName_Text {
            get {
                return ResourceManager.GetString("txtUserName.Text", resourceCulture);
            }
        }
    }
}
